name: Just Testing
on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - run: npm i -g ngrok
      - run: ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
      - run: ngrok http 3636 -log=ngrok.log >/dev/null &
      - run: sleep 1
      - run: cat ngrok.log

      - run: npm install
      - run: npm run serve
